# PURL configuration for http://purl.obolibrary.org/obo/ogsf

idspace: OGSF
base_url: /obo/ogsf

products:
- ogsf.owl: https://raw.githubusercontent.com/linikujp/OGSF/master/src/ogsf-merged.owl

term_browser: ontobee
example_terms:
- OGSF_0000000
